steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/jakob-troidl/motif-backend:latest', './neuronal_motifs/server' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/jakob-troidl/motif-frontend:latest', './neuronal_motifs/client' ]
images:
  - gcr.io/jakob-troidl/motif-backend:latest
  - gcr.io/jakob-troidl/motif-frontend:latest
timeout: 1800s
