steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'gcr.io/jakob-troidl/motif-frontend:latest',
            './neuronal_motifs/client' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/jakob-troidl/motif-frontend:latest' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instances update-container motif-frontend --zone=us-east1-b \
          --container-image gcr.io/jakob-troidl/motif-frontend:latest
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'gcr.io/jakob-troidl/motif-backend:latest',
            './neuronal_motifs/server' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/jakob-troidl/motif-backend:latest' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud compute instances update-container motif-backend --zone=us-east1-b \
          --container-image gcr.io/jakob-troidl/motif-backend:latest
images:
  - gcr.io/jakob-troidl/motif-backend:latest
  - gcr.io/jakob-troidl/motif-frontend:latest
timeout: 7200s
