name: neuronal-motifs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - fontconfig
  - h5py
  - networkit
  - numba
  - pandas
  - pykdtree
  - uvicorn
  - websockets
  - zarr
  - pip
  - pip:
      - dotmotif==0.11.0
      - navis
      - neuprint-python==0.4.24
      - google-cloud-storage
