name: neuronal-motifs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - fontconfig
  - h5py
  - networkit
  - numba
  - pandas
  - pykdtree
  - uvicorn
  - websockets
  - zarr
  - pip
  - git
  - pip:
      - git+https://github.com/aplbrain/dotmotif
      - navis
      - neuprint-python==0.4.24
