name: neuronal-motifs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - h5py
  - numba
  - pandas
  - pykdtree
  - zarr
  - pip
  - pip:
      - PyQt5==5.15.6
      - dotmotif==0.11.0
      - navis
      - neuprint-python==0.4.16
      - uvicorn[standard]
      - zarr
