name: neuronal-motifs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - h5py
  - numba
  - pandas
  - uvicorn
  - pip
  - pip:
      - PyQt5==5.15.6
      - dotmotif
      - line-profiler-pycharm
      - navis
      - neuprint-python
