name: neuronal-motifs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - fontconfig
  - h5py
  - networkit
  - numba
  - pandas
  - pykdtree
  - uvicorn
  - websockets
  - zarr
  - pip
  - git
  - pip:
      # tmp dependencies for dotmotif
      - py2neo
      - tamarind
      # end tmp dependencies
      - navis
      - neuprint-python==0.4.24
      - git+https://github.com/aplbrain/dotmotif

