name: neuronal-motifs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - h5py
  - numba
  - pandas
  - pykdtree
  - zarr
  - pip
  - fontconfig
  - pip:
      - dotmotif==0.11.0
      - navis
      - neuprint-python==0.4.24
      - uvicorn
      - zarr
      - networkit
